// <auto-generated />
using System;
using HealthClinic.CL.DbContextModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HealthClinic.CL.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20201206131241_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HealthClinic.CL.Model.ActionsAndBenefits.Message", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DateAction")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PharmacyName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Text")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            id = 1,
                            DateAction = "02/02/2020",
                            IsRemoved = false,
                            PharmacyName = "Apoteka Jankovic",
                            Text = "Message",
                            TimeStamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Doctor.DoctorNotification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("DoctorUserId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("DoctorUserId");

                    b.ToTable("DoctorNotifications");

                    b.HasData(
                        new
                        {
                            id = 3,
                            Data = "3. string",
                            DoctorUserId = 1
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Doctor.DoctorUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("dateOfBirth")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("firstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("isSpecialist")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ordination")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("salary")
                        .HasColumnType("double");

                    b.Property<string>("secondName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("speciality")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("uniqueCitizensidentityNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            id = 1,
                            city = "Grad",
                            dateOfBirth = "2/2/2020",
                            email = "email",
                            firstName = "Konstantin",
                            isSpecialist = false,
                            ordination = "Ordination 1",
                            password = "pass",
                            phoneNumber = "123",
                            salary = 200.0,
                            secondName = "Davidovic",
                            speciality = "Cardiology",
                            uniqueCitizensidentityNumber = "1234"
                        },
                        new
                        {
                            id = 2,
                            city = "Grad",
                            dateOfBirth = "2/2/2020",
                            email = "email",
                            firstName = "Novak",
                            isSpecialist = false,
                            ordination = "Ordination 1",
                            password = "pass",
                            phoneNumber = "123",
                            salary = 200.0,
                            secondName = "Maric",
                            speciality = "Pulmonology",
                            uniqueCitizensidentityNumber = "12345"
                        },
                        new
                        {
                            id = 3,
                            city = "Grad",
                            dateOfBirth = "2/2/2020",
                            email = "email",
                            firstName = "Milica",
                            isSpecialist = false,
                            ordination = "Ordination 1",
                            password = "pass",
                            phoneNumber = "123",
                            salary = 200.0,
                            secondName = "Tadic",
                            speciality = "Cardiology",
                            uniqueCitizensidentityNumber = "12346"
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Doctor.Operation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("DoctorUserId")
                        .HasColumnType("int");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<string>("RoomId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("end")
                        .HasColumnType("time(6)");

                    b.HasKey("id");

                    b.HasIndex("DoctorUserId");

                    b.HasIndex("PatientUserId");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Date = "03/03/2020",
                            DoctorUserId = 1,
                            PatientUserId = 2,
                            RoomId = "room1",
                            Start = new TimeSpan(0, 14, 0, 0, 0),
                            end = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            id = 2,
                            Date = "03/10/2020",
                            DoctorUserId = 2,
                            PatientUserId = 1,
                            RoomId = "room1",
                            Start = new TimeSpan(0, 15, 0, 0, 0),
                            end = new TimeSpan(0, 15, 15, 0, 0)
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Doctor.OperationReferral", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("OperationId")
                        .HasColumnType("int");

                    b.Property<string>("classify")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("comment")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("medicine")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("quantityPerDay")
                        .HasColumnType("int");

                    b.Property<string>("takeMedicineUntil")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.ToTable("OperationReferrals");

                    b.HasData(
                        new
                        {
                            id = 1,
                            OperationId = 1,
                            classify = "Operation",
                            comment = "Operation was successfull.",
                            medicine = "Hemomycin",
                            quantityPerDay = 1,
                            takeMedicineUntil = "15/09/2020"
                        },
                        new
                        {
                            id = 2,
                            OperationId = 2,
                            classify = "Operation",
                            comment = "Patient lost a lot of blood.",
                            medicine = "Amoxicillin",
                            quantityPerDay = 3,
                            takeMedicineUntil = "18/10/2020"
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Doctor.Referral", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("classify")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("comment")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("medicine")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("quantityPerDay")
                        .HasColumnType("int");

                    b.Property<string>("takeMedicineUntil")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Referrals");

                    b.HasData(
                        new
                        {
                            id = 1,
                            AppointmentId = 1,
                            classify = "classify",
                            comment = "Patient had slight heart arrhythmia.",
                            medicine = "Aspirin",
                            quantityPerDay = 3,
                            takeMedicineUntil = "25/02/2020"
                        },
                        new
                        {
                            id = 2,
                            AppointmentId = 2,
                            classify = "Appointment",
                            comment = "Patient had cold.",
                            medicine = "Brufen",
                            quantityPerDay = 1,
                            takeMedicineUntil = "11/05/2020"
                        },
                        new
                        {
                            id = 3,
                            AppointmentId = 3,
                            classify = "classify",
                            comment = "Patient had slight heart arrhythmia.",
                            medicine = "Aspirin",
                            quantityPerDay = 3,
                            takeMedicineUntil = "25/02/2020"
                        },
                        new
                        {
                            id = 4,
                            AppointmentId = 4,
                            classify = "Appointment",
                            comment = "Patient had cold.",
                            medicine = "Brufen",
                            quantityPerDay = 1,
                            takeMedicineUntil = "11/05/2020"
                        },
                        new
                        {
                            id = 5,
                            AppointmentId = 5,
                            classify = "classify",
                            comment = "Patient had slight heart arrhythmia.",
                            medicine = "Aspirin",
                            quantityPerDay = 3,
                            takeMedicineUntil = "25/02/2020"
                        },
                        new
                        {
                            id = 6,
                            AppointmentId = 6,
                            classify = "Appointment",
                            comment = "Patient had cold.",
                            medicine = "Brufen",
                            quantityPerDay = 1,
                            takeMedicineUntil = "11/05/2020"
                        },
                        new
                        {
                            id = 7,
                            AppointmentId = 7,
                            classify = "classify",
                            comment = "Patient had slight heart arrhythmia.",
                            medicine = "Aspirin",
                            quantityPerDay = 3,
                            takeMedicineUntil = "25/02/2020"
                        },
                        new
                        {
                            id = 8,
                            AppointmentId = 8,
                            classify = "Appointment",
                            comment = "Patient had cold.",
                            medicine = "Brufen",
                            quantityPerDay = 1,
                            takeMedicineUntil = "11/05/2020"
                        },
                        new
                        {
                            id = 9,
                            AppointmentId = 9,
                            classify = "classify",
                            comment = "Patient had slight heart arrhythmia.",
                            medicine = "Aspirin",
                            quantityPerDay = 3,
                            takeMedicineUntil = "25/02/2020"
                        },
                        new
                        {
                            id = 10,
                            AppointmentId = 10,
                            classify = "Appointment",
                            comment = "Patient had cold.",
                            medicine = "Brufen",
                            quantityPerDay = 1,
                            takeMedicineUntil = "11/05/2020"
                        },
                        new
                        {
                            id = 11,
                            AppointmentId = 11,
                            classify = "classify",
                            comment = "Patient had slight heart arrhythmia.",
                            medicine = "Aspirin",
                            quantityPerDay = 3,
                            takeMedicineUntil = "25/02/2020"
                        },
                        new
                        {
                            id = 12,
                            AppointmentId = 12,
                            classify = "Appointment",
                            comment = "Patient had cold.",
                            medicine = "Brufen",
                            quantityPerDay = 1,
                            takeMedicineUntil = "11/05/2020"
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Employee.Schedule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("employeeFirst")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("employeeLast")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("employeeid")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("isOnDuty")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("room")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("shiftId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("shiftId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            id = 1,
                            date = "03/03/2020",
                            employeeFirst = "EmployeeName",
                            employeeLast = "EmployeeSurname",
                            employeeid = "2",
                            isOnDuty = true,
                            room = "1",
                            shiftId = 1
                        },
                        new
                        {
                            id = 2,
                            date = "02/02/2020",
                            employeeFirst = "EmployeeName",
                            employeeLast = "EmployeeSurname",
                            employeeid = "1",
                            isOnDuty = true,
                            room = "1",
                            shiftId = 2
                        },
                        new
                        {
                            id = 3,
                            date = "02/02/2020",
                            employeeFirst = "EmployeeName",
                            employeeLast = "EmployeeSurname",
                            employeeid = "3",
                            isOnDuty = true,
                            room = "1",
                            shiftId = 1
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Employee.Shift", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("endTime")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("startTime")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            id = 1,
                            endTime = "16:00",
                            startTime = "14:00"
                        },
                        new
                        {
                            id = 2,
                            endTime = "12:30",
                            startTime = "12:00"
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Hospital.Equipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Equipment");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Equipment");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Equipment name",
                            quantity = 1
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Hospital.ModelEquipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("RoomId");

                    b.ToTable("ModelEquipment");
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Hospital.ModelMedicine", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("RoomId");

                    b.ToTable("ModelMedicine");
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Hospital.ModelRoom", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("modelRooms");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Data = "data",
                            EquipmentId = 1
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Hospital.Renovation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("endDate")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("room")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("startDate")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Renovation");

                    b.HasData(
                        new
                        {
                            id = 1,
                            endDate = "End Date",
                            room = "1",
                            startDate = "Start date"
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Hospital.Room", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("forUse")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("typeOfRoom")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            id = 1,
                            forUse = true,
                            typeOfRoom = "typeOfRoom"
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Manager.ManagerNotification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ManagerUserId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ManagerUserId");

                    b.ToTable("ManagerNotification");
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Manager.ManagerUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("dateOfBirth")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("firstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("salary")
                        .HasColumnType("double");

                    b.Property<string>("secondName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("uniqueCitizensidentityNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("ManagerUsers");

                    b.HasData(
                        new
                        {
                            id = 17,
                            city = "Grad",
                            dateOfBirth = "22/04/1993",
                            email = "email",
                            firstName = "Manager Name",
                            password = "pass",
                            phoneNumber = "123",
                            salary = 200.0,
                            secondName = "Manager Surname",
                            uniqueCitizensidentityNumber = "1234"
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Orders.DoctorsOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOrdered")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ManagersOrderid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ManagersOrderid");

                    b.ToTable("DoctorsOrders");

                    b.HasData(
                        new
                        {
                            id = 1,
                            DateEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = true,
                            IsOrdered = true,
                            IsUrgent = false
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Orders.FinishedOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("FinishedOrders");

                    b.HasData(
                        new
                        {
                            id = 1
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Orders.ManagersOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsOrdered")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id");

                    b.ToTable("ManagersOrders");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOrdered = true,
                            IsUrgent = true
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Orders.MedicineForOrdering", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("MedicinesForOrdering");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Description = "Medicine description",
                            Name = "Medicine name",
                            OrderId = 1,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Orders.PharmacyOffer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PharmacyName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("SummPriceOfMedications")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("PharmacyOffers");

                    b.HasData(
                        new
                        {
                            id = 1,
                            PharmacyName = "pharmacyName",
                            SummPriceOfMedications = 100.0
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Patient.DoctorAppointment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("DoctorUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<string>("RoomId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("time(6)");

                    b.HasKey("id");

                    b.HasIndex("DoctorUserId");

                    b.HasIndex("PatientUserId");

                    b.ToTable("DoctorAppointments");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Date = "03/03/2020",
                            DoctorUserId = 1,
                            IsCanceled = false,
                            PatientUserId = 2,
                            RoomId = "1",
                            Start = new TimeSpan(0, 14, 15, 0, 0)
                        },
                        new
                        {
                            id = 2,
                            Date = "03/03/2020",
                            DoctorUserId = 2,
                            IsCanceled = false,
                            PatientUserId = 2,
                            RoomId = "1",
                            Start = new TimeSpan(0, 14, 30, 0, 0)
                        },
                        new
                        {
                            id = 3,
                            Date = "03/03/2020",
                            DoctorUserId = 2,
                            IsCanceled = false,
                            PatientUserId = 1,
                            RoomId = "1",
                            Start = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            id = 4,
                            Date = "03/03/2020",
                            DoctorUserId = 2,
                            IsCanceled = false,
                            PatientUserId = 1,
                            RoomId = "1",
                            Start = new TimeSpan(0, 15, 45, 0, 0)
                        },
                        new
                        {
                            id = 5,
                            Date = "02/02/2020",
                            DoctorUserId = 1,
                            IsCanceled = false,
                            PatientUserId = 1,
                            RoomId = "1",
                            Start = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            id = 6,
                            Date = "02/02/2020",
                            DoctorUserId = 3,
                            IsCanceled = false,
                            PatientUserId = 2,
                            RoomId = "1",
                            Start = new TimeSpan(0, 12, 15, 0, 0)
                        },
                        new
                        {
                            id = 7,
                            Date = "07/02/2031",
                            DoctorUserId = 3,
                            IsCanceled = false,
                            PatientUserId = 1,
                            RoomId = "1",
                            Start = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            id = 8,
                            Date = "07/12/2020",
                            DoctorUserId = 2,
                            IsCanceled = false,
                            PatientUserId = 1,
                            RoomId = "1",
                            Start = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            id = 9,
                            Date = "05/12/2030",
                            DoctorUserId = 1,
                            IsCanceled = false,
                            PatientUserId = 1,
                            RoomId = "1",
                            Start = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            id = 10,
                            Date = "11/11/2030",
                            DoctorUserId = 2,
                            IsCanceled = false,
                            PatientUserId = 1,
                            RoomId = "1",
                            Start = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            id = 11,
                            Date = "14/03/2016",
                            DoctorUserId = 1,
                            IsCanceled = false,
                            PatientUserId = 2,
                            RoomId = "A2",
                            Start = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            id = 12,
                            Date = "11/11/2010",
                            DoctorUserId = 2,
                            IsCanceled = false,
                            PatientUserId = 2,
                            RoomId = "B3",
                            Start = new TimeSpan(0, 0, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Patient.Feedback", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PatientId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Date = new DateTime(2020, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAnonymous = true,
                            IsPublic = true,
                            IsPublished = false,
                            Message = "First message",
                            PatientId = 1
                        },
                        new
                        {
                            id = 2,
                            Date = new DateTime(2019, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAnonymous = false,
                            IsPublic = false,
                            IsPublished = false,
                            Message = "Second message",
                            PatientId = 1
                        },
                        new
                        {
                            id = 3,
                            Date = new DateTime(2020, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAnonymous = false,
                            IsPublic = true,
                            IsPublished = false,
                            Message = "Third message",
                            PatientId = 1
                        },
                        new
                        {
                            id = 4,
                            Date = new DateTime(2020, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAnonymous = false,
                            IsPublic = true,
                            IsPublished = false,
                            Message = "Fourth message",
                            PatientId = 1
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Patient.ModelNotification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PatientUserId");

                    b.ToTable("PatientNotifications");

                    b.HasData(
                        new
                        {
                            id = 3,
                            Data = "3. string",
                            PatientUserId = 1
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Patient.PatientUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("allergie")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("bornIn")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("city")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("dateOfBirth")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("exLastname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("file")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("firstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("gender")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("guest")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isMarried")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isRegisteredBySecretary")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("medicalIdNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("parentName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("secondName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("uniqueCitizensidentityNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            id = 1,
                            allergie = "Alergija",
                            bornIn = "Grad2",
                            city = "Grad",
                            dateOfBirth = "2/2/2020",
                            email = "email",
                            exLastname = "",
                            firstName = "Pera2",
                            gender = "Male",
                            guest = false,
                            isMarried = false,
                            isRegisteredBySecretary = false,
                            isVerified = false,
                            medicalIdNumber = "212313",
                            parentName = "Roditelj",
                            password = "pass",
                            phoneNumber = "123",
                            secondName = "Peric",
                            uniqueCitizensidentityNumber = "1234"
                        },
                        new
                        {
                            id = 2,
                            allergie = "Alergija",
                            bornIn = "Grad2",
                            city = "Grad",
                            dateOfBirth = "2/2/2020",
                            email = "email",
                            exLastname = "",
                            firstName = "Pera3",
                            gender = "Female",
                            guest = false,
                            isMarried = false,
                            isRegisteredBySecretary = false,
                            isVerified = false,
                            medicalIdNumber = "2112313",
                            parentName = "Roditelj",
                            password = "pass",
                            phoneNumber = "123",
                            secondName = "Peric",
                            uniqueCitizensidentityNumber = "1234"
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Patient.PhoneNumber", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("number")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("PhoneNumbers");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Name",
                            number = 123
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Patient.Prescription", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("isUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("patientsid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            id = 5,
                            DoctorId = 1,
                            comment = "Use every day",
                            isUsed = false,
                            patientsid = 1
                        },
                        new
                        {
                            id = 6,
                            DoctorId = 1,
                            comment = "When needed",
                            isUsed = true,
                            patientsid = 2
                        },
                        new
                        {
                            id = 7,
                            DoctorId = 2,
                            comment = "On every 12 hours",
                            isUsed = true,
                            patientsid = 1
                        },
                        new
                        {
                            id = 8,
                            DoctorId = 1,
                            comment = "After lunch",
                            isUsed = true,
                            patientsid = 1
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Patient.Question", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("answer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            id = 1,
                            answer = "Answer",
                            name = "Name"
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Patient.Survey", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("appointmentId")
                        .HasColumnType("int");

                    b.Property<int>("doctorsKnowledge")
                        .HasColumnType("int");

                    b.Property<int>("doctorsPoliteness")
                        .HasColumnType("int");

                    b.Property<int>("doctorsProfessionalism")
                        .HasColumnType("int");

                    b.Property<int>("doctorsSkill")
                        .HasColumnType("int");

                    b.Property<int>("doctorsTechnicality")
                        .HasColumnType("int");

                    b.Property<int>("doctorsWorkingPace")
                        .HasColumnType("int");

                    b.Property<int>("hospitalEnvironment")
                        .HasColumnType("int");

                    b.Property<int>("hospitalEquipment")
                        .HasColumnType("int");

                    b.Property<int>("hospitalHygiene")
                        .HasColumnType("int");

                    b.Property<int>("hospitalPrices")
                        .HasColumnType("int");

                    b.Property<int>("hospitalWaitingTime")
                        .HasColumnType("int");

                    b.Property<int>("medicalStaffsKnowledge")
                        .HasColumnType("int");

                    b.Property<int>("medicalStaffsPoliteness")
                        .HasColumnType("int");

                    b.Property<int>("medicalStaffsProfessionalism")
                        .HasColumnType("int");

                    b.Property<int>("medicalStaffsSkill")
                        .HasColumnType("int");

                    b.Property<int>("medicalStaffsTechnicality")
                        .HasColumnType("int");

                    b.Property<int>("medicalStaffsWorkingPace")
                        .HasColumnType("int");

                    b.Property<int>("patientId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("appointmentId");

                    b.HasIndex("patientId");

                    b.ToTable("Surveys");

                    b.HasData(
                        new
                        {
                            id = 1,
                            appointmentId = 3,
                            doctorsKnowledge = 4,
                            doctorsPoliteness = 5,
                            doctorsProfessionalism = 4,
                            doctorsSkill = 5,
                            doctorsTechnicality = 4,
                            doctorsWorkingPace = 5,
                            hospitalEnvironment = 3,
                            hospitalEquipment = 3,
                            hospitalHygiene = 2,
                            hospitalPrices = 2,
                            hospitalWaitingTime = 5,
                            medicalStaffsKnowledge = 5,
                            medicalStaffsPoliteness = 5,
                            medicalStaffsProfessionalism = 4,
                            medicalStaffsSkill = 5,
                            medicalStaffsTechnicality = 5,
                            medicalStaffsWorkingPace = 4,
                            patientId = 1
                        },
                        new
                        {
                            id = 2,
                            appointmentId = 4,
                            doctorsKnowledge = 5,
                            doctorsPoliteness = 5,
                            doctorsProfessionalism = 4,
                            doctorsSkill = 1,
                            doctorsTechnicality = 3,
                            doctorsWorkingPace = 5,
                            hospitalEnvironment = 1,
                            hospitalEquipment = 3,
                            hospitalHygiene = 3,
                            hospitalPrices = 3,
                            hospitalWaitingTime = 5,
                            medicalStaffsKnowledge = 5,
                            medicalStaffsPoliteness = 2,
                            medicalStaffsProfessionalism = 2,
                            medicalStaffsSkill = 2,
                            medicalStaffsTechnicality = 4,
                            medicalStaffsWorkingPace = 3,
                            patientId = 1
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Pharmacy.RegistrationInPharmacy", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApiKey")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<string>("Town")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            id = 1,
                            ApiKey = "api1",
                            Name = "Jankovic 1",
                            PharmacyId = 1,
                            Town = "Novi Sad"
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Secretary.SecretaryUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("dateOfBirth")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("firstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("room")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("salary")
                        .HasColumnType("double");

                    b.Property<string>("secondName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("uniqueCitizensidentityNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("SecretaryUsers");

                    b.HasData(
                        new
                        {
                            id = 1,
                            city = "Grad",
                            dateOfBirth = "12/12/2012",
                            email = "email",
                            firstName = "Secretary Name",
                            password = "pass",
                            phoneNumber = "123",
                            room = "Room",
                            salary = 133.0,
                            secondName = "Secretary Surname",
                            uniqueCitizensidentityNumber = "1234"
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Hospital.Medicine", b =>
                {
                    b.HasBaseType("HealthClinic.CL.Model.Hospital.Equipment");

                    b.Property<int?>("FinishedOrderid")
                        .HasColumnType("int");

                    b.Property<int?>("PharmacyOfferid")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("doctorId")
                        .HasColumnType("int");

                    b.Property<bool>("isConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.HasIndex("FinishedOrderid");

                    b.HasIndex("PharmacyOfferid");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("doctorId");

                    b.HasDiscriminator().HasValue("Medicine");

                    b.HasData(
                        new
                        {
                            id = 51,
                            name = "Pancef",
                            quantity = 44,
                            PrescriptionId = 5,
                            description = "For temperature",
                            doctorId = 1,
                            isConfirmed = false
                        },
                        new
                        {
                            id = 52,
                            name = "Defrinol",
                            quantity = 2,
                            PrescriptionId = 7,
                            description = "For headache",
                            doctorId = 1,
                            isConfirmed = false
                        },
                        new
                        {
                            id = 53,
                            name = "Brufen",
                            quantity = 2,
                            PrescriptionId = 8,
                            description = "For illness",
                            doctorId = 1,
                            isConfirmed = false
                        },
                        new
                        {
                            id = 54,
                            name = "Paracetamol",
                            quantity = 4,
                            PrescriptionId = 6,
                            description = "For illness",
                            doctorId = 1,
                            isConfirmed = false
                        });
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Hospital.OfferedMedicines", b =>
                {
                    b.HasBaseType("HealthClinic.CL.Model.Hospital.Medicine");

                    b.Property<double>("price")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("OfferedMedicines");
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Doctor.DoctorNotification", b =>
                {
                    b.HasOne("HealthClinic.CL.Model.Doctor.DoctorUser", "DoctorUser")
                        .WithMany("specialNotifications")
                        .HasForeignKey("DoctorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Doctor.Operation", b =>
                {
                    b.HasOne("HealthClinic.CL.Model.Doctor.DoctorUser", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthClinic.CL.Model.Patient.PatientUser", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Doctor.OperationReferral", b =>
                {
                    b.HasOne("HealthClinic.CL.Model.Doctor.Operation", null)
                        .WithOne("operationReferral")
                        .HasForeignKey("HealthClinic.CL.Model.Doctor.OperationReferral", "OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Doctor.Referral", b =>
                {
                    b.HasOne("HealthClinic.CL.Model.Patient.DoctorAppointment", null)
                        .WithMany("referral")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Employee.Schedule", b =>
                {
                    b.HasOne("HealthClinic.CL.Model.Employee.Shift", "shift")
                        .WithMany()
                        .HasForeignKey("shiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Hospital.ModelEquipment", b =>
                {
                    b.HasOne("HealthClinic.CL.Model.Hospital.Room", "Room")
                        .WithMany("equipment")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Hospital.ModelMedicine", b =>
                {
                    b.HasOne("HealthClinic.CL.Model.Hospital.Room", "Room")
                        .WithMany("medicine")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Hospital.ModelRoom", b =>
                {
                    b.HasOne("HealthClinic.CL.Model.Hospital.Equipment", "Equipment")
                        .WithMany("room")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Manager.ManagerNotification", b =>
                {
                    b.HasOne("HealthClinic.CL.Model.Manager.ManagerUser", "ManagerUser")
                        .WithMany("specialNotifications")
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Orders.DoctorsOrder", b =>
                {
                    b.HasOne("HealthClinic.CL.Model.Orders.ManagersOrder", null)
                        .WithMany("ListOfDoctorsOrders")
                        .HasForeignKey("ManagersOrderid");
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Patient.DoctorAppointment", b =>
                {
                    b.HasOne("HealthClinic.CL.Model.Doctor.DoctorUser", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthClinic.CL.Model.Patient.PatientUser", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Patient.Feedback", b =>
                {
                    b.HasOne("HealthClinic.CL.Model.Patient.PatientUser", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Patient.ModelNotification", b =>
                {
                    b.HasOne("HealthClinic.CL.Model.Patient.PatientUser", "PatientUser")
                        .WithMany("notifications")
                        .HasForeignKey("PatientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Patient.Prescription", b =>
                {
                    b.HasOne("HealthClinic.CL.Model.Doctor.DoctorUser", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Patient.Survey", b =>
                {
                    b.HasOne("HealthClinic.CL.Model.Patient.DoctorAppointment", "appointment")
                        .WithMany()
                        .HasForeignKey("appointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthClinic.CL.Model.Patient.PatientUser", "patient")
                        .WithMany()
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthClinic.CL.Model.Hospital.Medicine", b =>
                {
                    b.HasOne("HealthClinic.CL.Model.Orders.FinishedOrder", null)
                        .WithMany("ListOfMedicines")
                        .HasForeignKey("FinishedOrderid");

                    b.HasOne("HealthClinic.CL.Model.Orders.PharmacyOffer", null)
                        .WithMany("ListOfMedicies")
                        .HasForeignKey("PharmacyOfferid");

                    b.HasOne("HealthClinic.CL.Model.Patient.Prescription", "Prescription")
                        .WithMany("Medicines")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthClinic.CL.Model.Doctor.DoctorUser", "doctor")
                        .WithMany()
                        .HasForeignKey("doctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
