version: '3.4'

services:
  urgentmedicineorderapi:
    image: velickotam/healthcaresystem:urgentmedicinoerder_latest
    container_name: urgentmedicineorderapi
    restart: on-failure
    networks:
      - demo
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: MYSQLHealtcareDB
      DATABASE_PORT: 3306
      PORT: 59328
      STAGE: Development
    depends_on:
      - mysql
    volumes:
      - urgentmedicineorderapi:/app/sql

  eprescritionapi:
    image: velickotam/healthcaresystem:eprescrition_latest
    container_name: eprescritionapi
    restart: on-failure
    networks:
      - demo
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: MYSQLHealtcareDB
      DATABASE_PORT: 3306
      PORT: 63327
      STAGE: Development
    depends_on:
      - mysql
    volumes:
      - eprescritionapi:/app/sql

  gatewayintegration:
    image: velickotam/healthcaresystem:gatewayintegration_latest
    container_name: gatewayintegration
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - PORT=80
    networks:
      - demo
    ports:
      - 54679:80
    links:
      - pharmacyregistrationapi
      - urgentmedicineorderapi
      - medicineinformationapi
      - tenderapi
      - eprescritionapi
    depends_on:
      - pharmacyregistrationapi
      - urgentmedicineorderapi
      - medicineinformationapi
      - tenderapi
      - eprescritionapi

  medicineinformationapi:
    image:  velickotam/healthcaresystem:medicineinformation_latest
    container_name: medicineinformationapi
    restart: on-failure
    networks:
      - demo
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: MYSQLHealtcareDB
      DATABASE_PORT: 3306
      PORT: 50482
      STAGE: Development
    depends_on:
      - mysql
    volumes:
      - medicineinformationapi:/app/sql

  tenderapi:
    image: velickotam/healthcaresystem:tender_latest
    container_name: tenderapi
    restart: on-failure
    networks:
      - demo
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: MYSQLHealtcareDB
      DATABASE_PORT: 3306
      PORT: 50921
      STAGE: Development
    depends_on:
      - mysql
    volumes:
      - tenderapi:/app/sql


  pharmacyregistrationapi:
    image: velickotam/healthcaresystem:pharmacyregistration_latest
    container_name: pharmacyregistrationapi
    restart: on-failure
    networks:
      - demo
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: MYSQLHealtcareDB
      DATABASE_PORT: 3306
      PORT: 59278
      STAGE: Development
    depends_on:
      - mysql
    volumes:
      - pharmacyregistrationapi:/app/sql

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    networks:
      - demo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: MYSQLHealtcareDB
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  vue:
    image: velickotam/healthcaresystem:vue_latest
    container_name: vue
    stdin_open: true
    restart: on-failure
    networks:
      - demo
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: MYSQLHealtcareDB
      DATABASE_PORT: 3306
      PORT: 57942
    depends_on:
      - mysql
    volumes:
      - vue:/app/sql
    ports:
      - '57942:57942'

volumes:
  gatewayintegration:
  pharmacyregistrationapi:
  tenderapi:
  medicineinformationapi:
  urgentmedicineorderapi:
  eprescritionapi:
  mysql-data:
  vue:

networks:
  demo:
    name: demo
    driver: bridge
