#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["IntegrationWithPharmaciesIntegrationTests/IntegrationWithPharmaciesIntegrationTests.csproj", "IntegrationWithPharmaciesIntegrationTests/"]
COPY ["IntegrationWithPharmacies/IntegrationWithPharmacies.csproj", "IntegrationWithPharmacies/"]
COPY ["PatientWebApplication/HealthClinic.DAL/HealthClinic.CL.csproj", "PatientWebApplication/HealthClinic.DAL/"]
RUN dotnet restore "IntegrationWithPharmaciesIntegrationTests/IntegrationWithPharmaciesIntegrationTests.csproj"
COPY . .
WORKDIR "/src/IntegrationWithPharmaciesIntegrationTests"
RUN dotnet build "IntegrationWithPharmaciesIntegrationTests.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "IntegrationWithPharmaciesIntegrationTests.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "IntegrationWithPharmaciesIntegrationTests.dll"]