#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["PatientWebApplication/PatientWebApplicationIntegrationTests/PatientWebApplicationIntegrationTests.csproj", "PatientWebApplication/PatientWebApplicationIntegrationTests/"]
COPY ["PatientWebApplication/PatientWebApplication/PatientWebApplication.csproj", "PatientWebApplication/PatientWebApplication/"]
COPY ["PatientWebApplication/HealthClinic.DAL/HealthClinic.CL.csproj", "PatientWebApplication/HealthClinic.DAL/"]
RUN dotnet restore "PatientWebApplication/PatientWebApplicationIntegrationTests/PatientWebApplicationIntegrationTests.csproj"
COPY . .
WORKDIR "/src/PatientWebApplicationIntegrationTests"
RUN dotnet build "PatientWebApplicationIntegrationTests.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PatientWebApplicationIntegrationTests.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PatientWebApplicationIntegrationTests.dll"]