// <auto-generated />
using System;
using AppointmentMicroserviceApi.DbContextModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppointmentMicroserviceApi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AppointmentMicroserviceApi.Doctor.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("DoctorUserId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("time(6)");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<string>("RoomId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "23/12/2020",
                            DoctorUserId = 1,
                            End = new TimeSpan(0, 15, 0, 0, 0),
                            PatientUserId = 2,
                            RoomId = "room1",
                            Start = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Date = "03/10/2020",
                            DoctorUserId = 2,
                            End = new TimeSpan(0, 15, 15, 0, 0),
                            PatientUserId = 1,
                            RoomId = "room1",
                            Start = new TimeSpan(0, 15, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("AppointmentMicroserviceApi.Doctor.OperationReferral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("OperationId")
                        .HasColumnType("int");

                    b.Property<string>("Procedure")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.ToTable("OperationReferrals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diagnosis = "Bilateral upper eyelid dermatochalasis",
                            OperationId = 1,
                            Procedure = "This 65-year-old female demonstrates conditions described above of excess and redundant eyelid skin with puffiness and has requested surgical correction. The face was prepped and draped in the usual sterile manner. After waiting a period of approximately ten minutes for adequate vasoconstriction, the previously outlined excessive skin of the right upper eyelid was excised with blunt dissection. At the end of the operation the patientʼs vision and extraocular muscle movements were checked and found to be intact. The patient was released to return home in satisfactory condition."
                        },
                        new
                        {
                            Id = 2,
                            Diagnosis = " Stage IV breast cancer with left breast mass.",
                            OperationId = 2,
                            Procedure = "The patient was brought into the operative room and placed on the operative table in the supine position. General endotracheal anesthesia was administered, and the patient was prepped and draped in the usual sterile fashion. A large lumpectomy was performed around the palpable mass extending down to the level of the muscle. The wound was then closed in two layers approximating the deep dermal layer with 3-0 Vicryl and the skin with 4-0 Monocryl. Steri-Strips and dressings were applied. The patient was extubated and transported to the recovery area in stable condition."
                        });
                });

            modelBuilder.Entity("AppointmentMicroserviceApi.Doctor.Referral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Procedure")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Referrals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            Diagnosis = "Pneumonia",
                            Procedure = "Patient had temperature taken. Temperature was 39.6 degrees. Listened to patients breathing. Breathing was slightly constricted. Established that patient has lighter case of pneumonia. Sent home for home treatment."
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 2,
                            Diagnosis = "Concussion",
                            Procedure = "Patient had visible gash on back of his head. Patient complains of blurred vision. Established that patient has concussion. Left for a night of hospital observation"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 3,
                            Diagnosis = "Pneumonia",
                            Procedure = "Patient had temperature taken. Temperature was 39.6 degrees. Listened to patients breathing. Breathing was slightly constricted. Established that patient has lighter case of pneumonia. Sent home for home treatment."
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 4,
                            Diagnosis = "Concussion",
                            Procedure = "Patient had visible gash on back of his head. Patient complains of blurred vision. Established that patient has concussion. Left for a night of hospital observation"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 5,
                            Diagnosis = "Pneumonia",
                            Procedure = "Patient had temperature taken. Temperature was 39.6 degrees. Listened to patients breathing. Breathing was slightly constricted. Established that patient has lighter case of pneumonia. Sent home for home treatment."
                        },
                        new
                        {
                            Id = 6,
                            AppointmentId = 6,
                            Diagnosis = "Concussion",
                            Procedure = "Patient had visible gash on back of his head. Patient complains of blurred vision. Established that patient has concussion. Left for a night of hospital observation"
                        },
                        new
                        {
                            Id = 7,
                            AppointmentId = 7,
                            Diagnosis = "Pneumonia",
                            Procedure = "Patient had temperature taken. Temperature was 39.6 degrees. Listened to patients breathing. Breathing was slightly constricted. Established that patient has lighter case of pneumonia. Sent home for home treatment."
                        },
                        new
                        {
                            Id = 8,
                            AppointmentId = 8,
                            Diagnosis = "Concussion",
                            Procedure = "Patient had visible gash on back of his head. Patient complains of blurred vision. Established that patient has concussion. Left for a night of hospital observation"
                        },
                        new
                        {
                            Id = 9,
                            AppointmentId = 9,
                            Diagnosis = "Pneumonia",
                            Procedure = "Patient had temperature taken. Temperature was 39.6 degrees. Listened to patients breathing. Breathing was slightly constricted. Established that patient has lighter case of pneumonia. Sent home for home treatment."
                        },
                        new
                        {
                            Id = 10,
                            AppointmentId = 10,
                            Diagnosis = "Concussion",
                            Procedure = "Patient had visible gash on back of his head. Patient complains of blurred vision. Established that patient has concussion. Left for a night of hospital observation"
                        },
                        new
                        {
                            Id = 11,
                            AppointmentId = 11,
                            Diagnosis = "Pneumonia",
                            Procedure = "Patient had temperature taken. Temperature was 39.6 degrees. Listened to patients breathing. Breathing was slightly constricted. Established that patient has lighter case of pneumonia. Sent home for home treatment."
                        },
                        new
                        {
                            Id = 12,
                            AppointmentId = 12,
                            Diagnosis = "Concussion",
                            Procedure = "Patient had visible gash on back of his head. Patient complains of blurred vision. Established that patient has concussion. Left for a night of hospital observation"
                        });
                });

            modelBuilder.Entity("AppointmentMicroserviceApi.Patient.DoctorAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CancelDateString")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Date")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("DoctorUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<string>("RoomId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("DoctorAppointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "23/12/2020",
                            DoctorUserId = 1,
                            IsCanceled = false,
                            PatientUserId = 2,
                            RoomId = "1",
                            Start = new TimeSpan(0, 14, 15, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Date = "23/12/2020",
                            DoctorUserId = 2,
                            IsCanceled = false,
                            PatientUserId = 2,
                            RoomId = "1",
                            Start = new TimeSpan(0, 14, 30, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Date = "23/12/2020",
                            DoctorUserId = 2,
                            IsCanceled = false,
                            PatientUserId = 1,
                            RoomId = "1",
                            Start = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            Date = "23/12/2020",
                            DoctorUserId = 2,
                            IsCanceled = false,
                            PatientUserId = 1,
                            RoomId = "1",
                            Start = new TimeSpan(0, 15, 45, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            Date = "22/12/2020",
                            DoctorUserId = 1,
                            IsCanceled = false,
                            PatientUserId = 1,
                            RoomId = "1",
                            Start = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            Date = "22/12/2020",
                            DoctorUserId = 3,
                            IsCanceled = false,
                            PatientUserId = 2,
                            RoomId = "1",
                            Start = new TimeSpan(0, 12, 15, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            Date = "07/02/2031",
                            DoctorUserId = 3,
                            IsCanceled = false,
                            PatientUserId = 1,
                            RoomId = "1",
                            Start = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            Date = "07/12/2020",
                            DoctorUserId = 2,
                            IsCanceled = false,
                            PatientUserId = 1,
                            RoomId = "1",
                            Start = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            Date = "05/12/2030",
                            DoctorUserId = 1,
                            IsCanceled = false,
                            PatientUserId = 1,
                            RoomId = "1",
                            Start = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            Date = "11/11/2030",
                            DoctorUserId = 2,
                            IsCanceled = false,
                            PatientUserId = 1,
                            RoomId = "1",
                            Start = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            Date = "14/03/2016",
                            DoctorUserId = 1,
                            IsCanceled = false,
                            PatientUserId = 2,
                            RoomId = "A2",
                            Start = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            Date = "11/11/2010",
                            DoctorUserId = 2,
                            IsCanceled = false,
                            PatientUserId = 2,
                            RoomId = "B3",
                            Start = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            CancelDateString = "09/01/2021",
                            Date = "23/12/2020",
                            DoctorUserId = 2,
                            IsCanceled = true,
                            PatientUserId = 3,
                            RoomId = "1",
                            Start = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            CancelDateString = "09/01/2021",
                            Date = "23/12/2020",
                            DoctorUserId = 2,
                            IsCanceled = true,
                            PatientUserId = 3,
                            RoomId = "1",
                            Start = new TimeSpan(0, 15, 45, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            CancelDateString = "09/01/2021",
                            Date = "22/12/2020",
                            DoctorUserId = 1,
                            IsCanceled = true,
                            PatientUserId = 3,
                            RoomId = "1",
                            Start = new TimeSpan(0, 12, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("AppointmentMicroserviceApi.Patient.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Answer",
                            Name = "Name"
                        });
                });

            modelBuilder.Entity("AppointmentMicroserviceApi.Patient.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorsKnowledge")
                        .HasColumnType("int");

                    b.Property<int>("DoctorsPoliteness")
                        .HasColumnType("int");

                    b.Property<int>("DoctorsProfessionalism")
                        .HasColumnType("int");

                    b.Property<int>("DoctorsSkill")
                        .HasColumnType("int");

                    b.Property<int>("DoctorsTechnicality")
                        .HasColumnType("int");

                    b.Property<int>("DoctorsWorkingPace")
                        .HasColumnType("int");

                    b.Property<int>("HospitalEnvironment")
                        .HasColumnType("int");

                    b.Property<int>("HospitalEquipment")
                        .HasColumnType("int");

                    b.Property<int>("HospitalHygiene")
                        .HasColumnType("int");

                    b.Property<int>("HospitalPrices")
                        .HasColumnType("int");

                    b.Property<int>("HospitalWaitingTime")
                        .HasColumnType("int");

                    b.Property<int>("MedicalStaffsKnowledge")
                        .HasColumnType("int");

                    b.Property<int>("MedicalStaffsPoliteness")
                        .HasColumnType("int");

                    b.Property<int>("MedicalStaffsProfessionalism")
                        .HasColumnType("int");

                    b.Property<int>("MedicalStaffsSkill")
                        .HasColumnType("int");

                    b.Property<int>("MedicalStaffsTechnicality")
                        .HasColumnType("int");

                    b.Property<int>("MedicalStaffsWorkingPace")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Surveys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 3,
                            DoctorsKnowledge = 4,
                            DoctorsPoliteness = 5,
                            DoctorsProfessionalism = 4,
                            DoctorsSkill = 5,
                            DoctorsTechnicality = 4,
                            DoctorsWorkingPace = 5,
                            HospitalEnvironment = 3,
                            HospitalEquipment = 3,
                            HospitalHygiene = 2,
                            HospitalPrices = 2,
                            HospitalWaitingTime = 5,
                            MedicalStaffsKnowledge = 5,
                            MedicalStaffsPoliteness = 5,
                            MedicalStaffsProfessionalism = 4,
                            MedicalStaffsSkill = 5,
                            MedicalStaffsTechnicality = 5,
                            MedicalStaffsWorkingPace = 4,
                            PatientId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 4,
                            DoctorsKnowledge = 5,
                            DoctorsPoliteness = 5,
                            DoctorsProfessionalism = 4,
                            DoctorsSkill = 1,
                            DoctorsTechnicality = 3,
                            DoctorsWorkingPace = 5,
                            HospitalEnvironment = 1,
                            HospitalEquipment = 3,
                            HospitalHygiene = 3,
                            HospitalPrices = 3,
                            HospitalWaitingTime = 5,
                            MedicalStaffsKnowledge = 5,
                            MedicalStaffsPoliteness = 2,
                            MedicalStaffsProfessionalism = 2,
                            MedicalStaffsSkill = 2,
                            MedicalStaffsTechnicality = 4,
                            MedicalStaffsWorkingPace = 3,
                            PatientId = 1
                        });
                });

            modelBuilder.Entity("AppointmentMicroserviceApi.Doctor.OperationReferral", b =>
                {
                    b.HasOne("AppointmentMicroserviceApi.Doctor.Operation", null)
                        .WithOne("OperationReferral")
                        .HasForeignKey("AppointmentMicroserviceApi.Doctor.OperationReferral", "OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentMicroserviceApi.Doctor.Referral", b =>
                {
                    b.HasOne("AppointmentMicroserviceApi.Patient.DoctorAppointment", null)
                        .WithMany("Referral")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentMicroserviceApi.Patient.Survey", b =>
                {
                    b.HasOne("AppointmentMicroserviceApi.Patient.DoctorAppointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
