// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientWebApplication.Models;

namespace PatientWebApplication.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20201105161128_FourthMigration")]
    partial class FourthMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Class_diagram.Model.Patient.Feedback", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PatientId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            id = 1,
                            IsAnonymous = true,
                            IsPublic = true,
                            IsPublished = false,
                            Message = "First message",
                            PatientId = 1
                        },
                        new
                        {
                            id = 2,
                            IsAnonymous = false,
                            IsPublic = false,
                            IsPublished = false,
                            Message = "Second message",
                            PatientId = 1
                        },
                        new
                        {
                            id = 3,
                            IsAnonymous = false,
                            IsPublic = true,
                            IsPublished = false,
                            Message = "Third message",
                            PatientId = 1
                        });
                });

            modelBuilder.Entity("Class_diagram.Model.Patient.PatientUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("allergie")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("city")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("dateOfBirth")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("firstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("guest")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isRegisteredBySecretary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("medicalIdNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("secondName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("uniqueCitizensidentityNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            id = 1,
                            allergie = "Alergija",
                            city = "Grad",
                            dateOfBirth = "2/2/2020",
                            email = "email",
                            firstName = "Pera",
                            guest = false,
                            isRegisteredBySecretary = false,
                            medicalIdNumber = "1234",
                            password = "pass",
                            phoneNumber = "123",
                            secondName = "Peric",
                            uniqueCitizensidentityNumber = "1234"
                        });
                });

            modelBuilder.Entity("HCI_wireframe.Model.Doctor.DoctorNotification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("DoctorUserId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("DoctorUserId");

                    b.ToTable("DoctorNotifications");

                    b.HasData(
                        new
                        {
                            id = 3,
                            Data = "3. string",
                            DoctorUserId = 1
                        });
                });

            modelBuilder.Entity("HCI_wireframe.Model.Doctor.DoctorUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("dateOfBirth")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("firstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("isSpecialist")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ordination")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("salary")
                        .HasColumnType("double");

                    b.Property<string>("secondName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("speciality")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("uniqueCitizensidentityNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            id = 1,
                            city = "Grad",
                            dateOfBirth = "2/2/2020",
                            email = "email",
                            firstName = "DoctorName",
                            isSpecialist = false,
                            ordination = "Ordination 1",
                            password = "pass",
                            phoneNumber = "123",
                            salary = 200.0,
                            secondName = "DoctorSurname",
                            speciality = "Specialty",
                            uniqueCitizensidentityNumber = "1234"
                        });
                });

            modelBuilder.Entity("HCI_wireframe.Model.Patient.ModelNotification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PatientUserId");

                    b.ToTable("PatientNotifications");

                    b.HasData(
                        new
                        {
                            id = 3,
                            Data = "3. string",
                            PatientUserId = 1
                        });
                });

            modelBuilder.Entity("Class_diagram.Model.Patient.Feedback", b =>
                {
                    b.HasOne("Class_diagram.Model.Patient.PatientUser", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HCI_wireframe.Model.Doctor.DoctorNotification", b =>
                {
                    b.HasOne("HCI_wireframe.Model.Doctor.DoctorUser", "DoctorUser")
                        .WithMany("specialNotifications")
                        .HasForeignKey("DoctorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HCI_wireframe.Model.Patient.ModelNotification", b =>
                {
                    b.HasOne("Class_diagram.Model.Patient.PatientUser", "PatientUser")
                        .WithMany("notifications")
                        .HasForeignKey("PatientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
